name:   'PixelCog Blog'
url:    'http://pixelcog.com'
author: 'Mike Greiling'

gems: [jekyll-paginate]

include:  ['_pages']

paginate:      10
paginate_path: '/blog/page:num/'
permalink:     '/blog/:year/:title/'

excerpt_separator: "{{ more }}"

markdown: 'kramdown'
timezone: 'America/Chicago'
highlighter: 'rouge'
